name: Publish to npm

# Triggers when a new release is published on GitHub
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Required for npm provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:run

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access=public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

# Setup Instructions:
# 1. Create an npm access token:
#    - Go to https://www.npmjs.com/settings/YOUR_USERNAME/tokens
#    - Click "Generate New Token" → "Classic Token"
#    - Select "Automation" type
#    - Copy the token
#
# 2. Add token to GitHub secrets:
#    - Go to your repo: Settings → Secrets and variables → Actions
#    - Click "New repository secret"
#    - Name: NPM_TOKEN
#    - Value: paste your npm token
#
# 3. Create a release to trigger publish:
#    - Update version: npm version patch (or minor/major)
#    - Push with tags: git push && git push --tags
#    - Go to GitHub repo → Releases → "Draft a new release"
#    - Select your tag, add release notes
#    - Click "Publish release"
#    - GitHub Actions will automatically build and publish to npm!
